### ISSUE TITLE
Table: data parameter ignores changes after init

### ISSUE THREAD

**Issue by Kraku** [resin-io-modules/rendition#502]
**Describe the bug**
When render function gets triggered with new data (props) table remains unchanged.

**To Reproduce**
```js
render() {
    let brightness, active;

    if (this.props.devices.length > 0) {
      brightness = this.props.devices[0].brightness;
      active = this.props.devices[0].active;
    }

    return (
      <div className="ContentTable">
        <p>First element:</p>
        <p>Brightness: {brightness}, Active: {active ? 'yes' : 'nope'}</p>

        <hr />

        <Table columns={this.columns} 
               data={this.props.devices} />
      </div>
    );
  }
```

**Expected behavior**
Table content should be updated when new data comes.

**Screenshots**
Before props update:
<img width="406" alt="screen shot 2018-07-15 at 1 50 34 pm" src="https://user-images.githubusercontent.com/4125286/42733729-e0c2e00a-8836-11e8-87a0-850d1367ef44.png">
After props update:
<img width="381" alt="screen shot 2018-07-15 at 1 50 46 pm" src="https://user-images.githubusercontent.com/4125286/42733728-e0a517be-8836-11e8-96ce-f23e8ba32383.png">

**Specifications (please complete the following information):**
  - Browser: Chrome 67
  - OS: macOS sierra
  - Environment: production

**Comment by thgreasi** [comment]
Hi,
Could you include the whole [table column definition](https://github.com/resin-io-modules/rendition/blob/52bacec277c1cc5da9673114eb5cbcb72d281e9b/typings/rendition.d.ts#L412-L421)?

> When render function gets triggered with new data (props) table remains unchanged.

If the row doesn't get updated, then probably the respective `render()` method of the column definition object doesn't get called when the aforementioned change takes place. Could you confirm that (eg by adding some `console.log`s`)?

The [`render()`](https://github.com/resin-io-modules/rendition/blob/52bacec277c1cc5da9673114eb5cbcb72d281e9b/typings/rendition.d.ts#L419) method is invoked with two parameters, the value that's stored in the [`field`](https://github.com/resin-io-modules/rendition/blob/52bacec277c1cc5da9673114eb5cbcb72d281e9b/typings/rendition.d.ts#L416) property of the row item and the row item itself.
In order to reduce re-renders, each row get's rendered (by the `render()` method) only when the provided item has changed (using `_.isEqual`). As a result, your `render()` method should not rely on other scope variables, but just on its properties.

I would suggest you to change your presentational model (the row item object) to include all properties that are needed for it to get rendered. Otherwise you could cause a re-render of the whole table by passing a fresh table.

Give me a note on whether the above resolve your issue and perhaps we could close this.

**Comment by LucianBuzzo** [comment]
@Kraku It's worth bearing in mind that mutating a value used as a property can cause some tricky bugs. 
When a component is using `shouldComponentUpdate` and compares `nextProps` to `this.props` to decide if it should update, if the inspected property has been mutated then the two values will be equal and the component will never update. This is because the mutation causes the value of `this.props` to change before the lifecycle event is triggered.

In my experience, this tends to happen when mutating an object in an array, using an index accessor, or falsely assuming that the spread operator performs a deep clone on an array - for example:
```
const original = [{
	foo: 'bar',
}]
// A new array is created, but the object is still the same
const clone = [ ...original ]
original[0].foo = 'baz'
console.log(clone[0].foo) // --> 'baz'
```

I've added some additional tests for the `Table` component to ensure that it works as expected here, please feel free to review them if you think I've missed anything https://github.com/resin-io-modules/rendition/pull/505

**Comment by jrsakizci** [comment]
Hello, this issue needs to be fixed immediately. I stopped my development because of this. I am changing data programmitically and react re-renders component but table component does not until i click sort(make table update collection itself)

**Comment by LucianBuzzo** [comment]
@jrsakizci Please post the code you are using to change your data

**Comment by jrsakizci** [comment]
@LucianBuzzo 
`
        const newData = this.state.data.slice();
        newData[index].active = !newData[index].active;
        this.setState({
            data: newData
      })
`

**Comment by LucianBuzzo** [comment]
@jrsakizci Is `newData` an object or an array? `Object.assign` will not clone an array. 
Can you try using the lodash `_.cloneDeep()` method? https://lodash.com/docs/4.17.10#cloneDeep
```js
const newData = _.cloneDeep(this.state.data)
// Perform update operations after clone so you don't cause mutation
// work...
this.setState({ data: newData })
```

**Comment by jrsakizci** [comment]
@LucianBuzzo i didnt want to use cloneDeep or immutability-helper but, thanks anyway im gonna use one of the helpers. Have a good day, sir.

**Comment by LucianBuzzo** [comment]
@jrsakizci If you want to avoid clonedeep or similar, then try using `Object.assign` on the data array element you would like to change, so instead of mutating the element like this:
```js
newData[index].active = !newData[index].active;
```
You assign a new element like this
```js
const element = newData[index]
newData[index] = Object.assign({}, element, { active: !element.active })
```

**Comment by LucianBuzzo** [comment]
I've dug into this a bit more, and I think I have a workaround that will prevent unnecessary row re-renders whilst still allowing the more intuitive prop mutation approach.

**Comment by LucianBuzzo** [comment]
After some discussion between myself and @thgreasi we've decided to leave the implementation as it is, as alternatives impact performance too heavily. I will update the documentation to better explain the behaviour of this component and best practices for implementing it in your apps.
